/**
 * utils/gemini.js
 * Travel Assistant backend utility powered by Google Gemini Flash.
 * Securely keeps API keys and model configuration on the server.
 */

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function getApiKey() {
    if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === "YOUR_GEMINI_API_KEY") {
        try {
            require("dotenv").config({ override: true });
        } catch (_) {}
    }
    return process.env.GEMINI_API_KEY;
}

function getModel() {
    const model = process.env.GEMINI_MODEL;
    return (model && model !== "YOUR_GEMINI_FLASH_MODEL" && model.trim() !== "")
        ? model.trim()
        : "gemini-3.1-flash-lite";
}

/**
 * Checks if a real, valid API key is present
 */
function isKeyConfigured() {
    const key = getApiKey();
    return Boolean(
        key &&
        key !== "YOUR_GEMINI_API_KEY" &&
        key.trim() !== ""
    );
}

/**
 * Execute call to Gemini REST API securely from server with retry & error handling:
 * - 429 / quota: no retry, returns clear quota message
 * - 503 / temporary network errors: capped exponential backoff (waitTime = (2 ** attempt) + 2)
 * - Max 3 attempts, server logging of retries, no API key exposure
 */
async function callGemini(prompt) {
    if (!isKeyConfigured()) {
        return null;
    }

    const apiKey = getApiKey();
    const model = getModel();
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    const maxRetries = 3;

    for (let attempt = 0; attempt < maxRetries; attempt++) {
        // Capped exponential backoff: waitTime = (2 ** attempt) + 2 seconds
        const waitTimeSec = Math.min((2 ** attempt) + 2, 30);
        const waitTimeMs = waitTimeSec * 1000;

        try {
            const response = await fetch(endpoint, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "x-goog-api-key": apiKey
                },
                body: JSON.stringify({
                    contents: [
                        {
                            parts: [{ text: prompt }]
                        }
                    ],
                    generationConfig: {
                        temperature: 0.7,
                        maxOutputTokens: 1500
                    }
                })
            });

            // 429 Quota / Rate Limit reached: do NOT retry; immediately return a clear message
            if (response.status === 429) {
                console.warn("[Gemini Assistant] HTTP 429 Quota / Rate limit reached. Aborting retries.");
                throw new Error("Gemini API rate limit or quota has been reached. Please check your usage quota or try again in a few moments.");
            }

            // 503 or 5xx temporary server/availability errors: use capped exponential backoff
            if (response.status === 503 || response.status === 502 || response.status === 504 || response.status === 500) {
                const errorBody = await response.text();
                const isQuota = errorBody.toLowerCase().includes("quota") || errorBody.toLowerCase().includes("exhausted");
                if (isQuota) {
                    throw new Error("Gemini API rate limit or quota has been reached. Please check your usage quota or try again in a few moments.");
                }

                if (attempt < maxRetries - 1) {
                    console.log(`[Gemini Assistant] HTTP ${response.status} temporary server error. Attempt ${attempt + 1}/${maxRetries}. Retrying in ${waitTimeSec}s (exponential backoff)...`);
                    await sleep(waitTimeMs);
                    continue;
                } else {
                    console.warn(`[Gemini Assistant] All ${maxRetries} retry attempts failed for HTTP ${response.status}.`);
                    throw new Error("Unable to reach Gemini AI service due to temporary high server demand. Please try again shortly.");
                }
            }

            if (!response.ok) {
                const errorText = await response.text();
                if (errorText.toLowerCase().includes("quota") || errorText.toLowerCase().includes("exhausted")) {
                    throw new Error("Gemini API rate limit or quota has been reached. Please check your usage quota or try again in a few moments.");
                }
                throw new Error(`Gemini service error (${response.status})`);
            }

            const data = await response.json();
            const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
            if (!text) {
                throw new Error("No response generated by Gemini model.");
            }
            return text;

        } catch (err) {
            // Quota / rate limit errors: abort immediately without retrying
            if (err.message && err.message.includes("rate limit or quota")) {
                throw err;
            }

            // Check for temporary network / SSL / connection errors
            const errMsg = (err.message || "").toLowerCase();
            const isNetworkError = err.code === "ECONNRESET" ||
                                   err.code === "ETIMEDOUT" ||
                                   err.code === "ENOTFOUND" ||
                                   errMsg.includes("fetch failed") ||
                                   errMsg.includes("network") ||
                                   errMsg.includes("ssl") ||
                                   errMsg.includes("socket") ||
                                   errMsg.includes("disconnected") ||
                                   errMsg.includes("unavailable");

            if (isNetworkError && attempt < maxRetries - 1) {
                console.log(`[Gemini Assistant] Temporary network error (${err.message}). Attempt ${attempt + 1}/${maxRetries}. Retrying in ${waitTimeSec}s (exponential backoff)...`);
                await sleep(waitTimeMs);
                continue;
            }

            if (attempt >= maxRetries - 1) {
                console.warn(`[Gemini Assistant] All ${maxRetries} attempts failed: ${err.message}`);
                if (err.message && err.message.startsWith("Unable to reach Gemini AI service")) {
                    throw err;
                }
                throw new Error("Unable to reach Gemini AI service due to a temporary network issue. Please check your connection and try again.");
            }

            throw err;
        }
    }
}

/**
 * Generates simulated structured plan when placeholder key is used
 */
function generateSimulatedTripPlan({ startLocation, destination, budget, days }) {
    const numDays = Math.max(1, parseInt(days) || 3);
    const dayPlans = [];
    for (let i = 1; i <= numDays; i++) {
        if (i === 1) {
            dayPlans.push(`- **Day 1:** Arrival in ${destination} from ${startLocation}, check-in to accommodation, explore the local market, and enjoy a relaxed welcome dinner.`);
        } else if (i === numDays) {
            dayPlans.push(`- **Day ${i}:** Morning leisure walk / souvenir shopping, local brunch, and return journey towards ${startLocation}.`);
        } else {
            dayPlans.push(`- **Day ${i}:** Full day sightseeing covering top cultural landmarks, famous scenic viewpoints, and authentic regional cuisine.`);
        }
    }

    return `### ✈️ Travel Plan: ${startLocation} → ${destination} (${numDays} Days)

*(Note: Live Google Gemini is configured in .env. To enable real-time AI responses, update \`GEMINI_API_KEY\` in your \`.env\` file. Below is your structured plan based on your inputs.)*

---

#### 1. 🚆 Suggested Way of Travelling
- **Recommended Transit:** Depending on distance, high-speed train or express flight from ${startLocation} to ${destination} is most time-efficient. For scenic routes under 300km, intercity bus or self-drive is a great option.
- **Local Commute:** Use local metro, shared cabs, or rental scooters to keep local transit hassle-free.

#### 2. 🗺️ Approximate Route & Sequence
- **Start:** Departure from **${startLocation}**
- **Transit Hub:** Arrival at ${destination} Central / Airport
- **Zone 1:** Downtown & Heritage District
- **Zone 2:** Scenic Nature / Coastline / Mountain Highlights
- **Return:** Departure from ${destination} back to **${startLocation}**

#### 3. 📍 Key Places to Visit
- **Historic & Cultural:** Iconic local monuments and heritage buildings
- **Scenic Highlights:** Popular viewpoints, waterfronts, or nature parks
- **Food & Shopping:** Famous street food lanes and vibrant evening craft bazaars

#### 4. 📅 Day-wise Travel Plan
${dayPlans.join("\n")}

#### 5. 💡 Budget-Aware Suggestions (${budget ? `Budget: ${budget}` : "Cost-Effective Tips"})
- **Accommodation:** Book verified Wanderlust homestays or boutique stays slightly away from tourist epicenters to save 25–40%.
- **Dining:** Eat at popular local eateries and verified street vendors rather than hotel restaurants for authentic flavor at a fraction of the cost.
- **Passes:** Check for public transit day passes or combined attraction tickets.`;
}

/**
 * Generates simulated nearby recommendations when placeholder key is used
 */
function generateSimulatedNearbyGuide({ location }) {
    return `### 📍 Local Guide for ${location}

*(Note: Live Google Gemini is configured in .env. To enable real-time AI responses, update \`GEMINI_API_KEY\` in your \`.env\` file. Below is your structured local guide based on your location.)*

---

#### 1. 🏛️ Top Nearby Tourist Attractions
- **Historic Landmarks:** Iconic architectural structures, palaces, or forts in and around ${location}.
- **Scenic Spots:** Famous public gardens, riverfronts, lake promenades, or hillside lookouts.
- **Museums & Art:** Renowned regional cultural and heritage centers.

#### 2. 🌟 Well-Known & Famous Places to Visit Nearby
- **Old Town / Central Bazaar:** Bustling traditional streets famous for handicrafts, textiles, and street delicacies.
- **Popular Walkways:** Famous pedestrian streets with historic architecture and vibrant cafes.
- **Evening Hotspot:** Sunset viewpoints and illuminated landmark areas frequented by travelers.

#### 3. 🏨 Popular Hotel & Accommodation Suggestions
- **Wanderlust Verified Stays:** Explore cozy apartments and private villas on Wanderlust in ${location}.
- **Heritage & Boutique Properties:** Character-rich boutique guesthouses near the city center.
- **Budget-Friendly Choices:** Clean, well-rated traveler hostels and bed-and-breakfasts near public transit.`;
}

/**
 * Plan a trip using Gemini Flash with retry & error handling
 */
async function planTrip({ startLocation, destination, budget, days }) {
    const prompt = `You are Wanderlust's Travel Assistant, a friendly and knowledgeable AI travel planner.
Create a simple, structured travel plan for:
- Starting Location: ${startLocation}
- Travel Destination: ${destination}
- Approximate Budget: ${budget || "Moderate"}
- Duration: ${days || 3} days

Please structure your response with these exact sections:
1. 🚆 Suggested Way of Travelling (transit options, route)
2. 🗺️ Approximate Route & Sequence
3. 📍 Key Places to Visit
4. 📅 Day-wise Travel Plan (Day 1 to Day ${days})
5. 💡 Budget-Aware Suggestions (money-saving tips, food, stay)

Keep the response concise, engaging, and cleanly formatted with bullet points.`;

    try {
        const liveResponse = await callGemini(prompt);
        if (liveResponse) {
            return { plan: liveResponse, isLive: true };
        }
    } catch (err) {
        console.warn(`[Gemini Assistant] Error handled: ${err.message}`);
        return {
            plan: `⚠️ **Travel Assistant Notice:** ${err.message}`,
            isLive: false,
            error: err.message
        };
    }

    return {
        plan: generateSimulatedTripPlan({ startLocation, destination, budget, days }),
        isLive: false
    };
}

/**
 * Get nearby places using Gemini Flash with retry & error handling
 */
async function getNearbyPlaces({ location }) {
    const prompt = `You are Wanderlust's Travel Assistant.
The user is at or near: ${location}.
Provide simple recommendations for this area:
1. 🏛️ Top Nearby Tourist Attractions (within easy reach)
2. 🌟 Well-known & Famous Places to Visit Nearby
3. 🏨 Popular Hotel & Accommodation Suggestions for travellers

Keep the response concise, structured, and cleanly formatted with bullet points.`;

    try {
        const liveResponse = await callGemini(prompt);
        if (liveResponse) {
            return { plan: liveResponse, isLive: true };
        }
    } catch (err) {
        console.warn(`[Gemini Assistant] Error handled: ${err.message}`);
        return {
            plan: `⚠️ **Travel Assistant Notice:** ${err.message}`,
            isLive: false,
            error: err.message
        };
    }

    return {
        plan: generateSimulatedNearbyGuide({ location }),
        isLive: false
    };
}

module.exports = {
    planTrip,
    getNearbyPlaces,
    isKeyConfigured
};
